base_url = "https://rse-rs.github.io"
title = "rse-rs"
description = "A Research Software Engineer Rust community"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[slugify]
paths_keep_dates = true

[extra]
feedback_url = "https://rse-rs.github.io/feedback" 
source_url = "https://github.com/rse-rs/rse-rs.github.io"
chat_url = "example.com"

